### ISSUE TITLE
[Links] Product Hunt Newsletter links open the same page. 

### ISSUE THREAD

**Issue by grub-basket** [arunkumar9t2/chromer#27]
This bug was fixed in a previous version of Chromer, but for some links, this has appeared to persist in the latest version. 

To clarify, if I open any link in an email by Product Hunt, they will all lead to the same page.

**Comment by arunkumar9t2** [comment]
Could you please leave some sample links here so that I can look into it?

**Comment by grub-basket** [comment]
I can't now, because whenever I try to launch Chromer, it says that `Chrome has Stopped Working` However, Google Chrome works as expected. What information could I provide that would be helpful?

**Comment by arunkumar9t2** [comment]
Yeah, I investigated that crash issue and found it might be due to a bug in Google Chrome. Google team have already fixed that and Chrome beta now doesn't crash. Once their fix reaches stable, it should work fine. At the moment, you can disable Bottom Bar in Chromer's settings to launch Chrome normally. 


About the Product Hunt issue, could you leave some sample Product Hunt links here for which you face the issue, so I can try to repro? 

The latest version is 1.7.3 Beta which was released yesterday.

**Comment by grub-basket** [comment]
Thanks for fixing the issue with it crashing. I wasn't able to reproduce any issues with the newsletters but will let you know if they reappear.

**Comment by arunkumar9t2** [comment]
Thanks, closing this for now.
