### ISSUE TITLE
Match color in recents with action

### ISSUE THREAD

**Issue by Thaodan** [arunkumar9t2/chromer#44]
The color of the recent card of chromer should match that of the action bar if possible.

**Comment by arunkumar9t2** [comment]
Thanks, I have made lot of improvements to the way task descriptions (color, title and icons) are handled in 2.0. One case which is not possible to fix is when the link the opened for the first time. When opening the first time, Chromer learns the color for the website but not possible to update the custom tab due to technical limitations. However when you open it the second time, it should match the toolbar and also recents card will match.

Closing the issue now, please feel free to open if you have doubts. You can test the changes in 2.0 which will launch shortly.
